package model;
// Generated 15/09/2016 15:10:23 by Hibernate Tools 4.3.1

/**
 * Requisitos generated by hbm2java
 */
public class Requisitos implements java.io.Serializable {

    private int requisitosId;
    private RequisitosProjeto requisitosProjeto;
    private String status;

    public Requisitos() {

    }

    public Requisitos(int requisitosId, RequisitosProjeto requisitosProjeto) {
        this.requisitosId = requisitosId;
        this.requisitosProjeto = requisitosProjeto;
    }

    public Requisitos(int requisitosId, RequisitosProjeto requisitosProjeto, String status) {
        this.requisitosId = requisitosId;
        this.requisitosProjeto = requisitosProjeto;
        this.status = status;
    }

    public int getRequisitosId() {
        return this.requisitosId;
    }

    public void setRequisitosId(int requisitosId) {
        this.requisitosId = requisitosId;
    }

    public RequisitosProjeto getRequisitosProjeto() {
        return this.requisitosProjeto;
    }

    public void setRequisitosProjeto(RequisitosProjeto requisitosProjeto) {
        this.requisitosProjeto = requisitosProjeto;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
